"Resource/UI/HudDemomanCharge.res"
{	

//G-Mang HUD

	"ChargeMeter"
	{	
		"ControlName"	"ContinuousProgressBar"
		"fieldName"		"ChargeMeter"
		"font"			"Default"
		"xpos"			"c-90"
		"ypos"			"r115"
		"zpos"			"2"
		"wide"			"180"
		"tall"			"7"				
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"textAlignment"	"Left"
		"dulltext"		"0"
		"brighttext"	"0"
	}
	"StickyBarVoid"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarVoid"
		"xpos"			"c-90"
		"ypos"			"r115"
		"zpos"			"-10"
		"wide"			"180"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyVoid"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit9f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit9f"
		"xpos"			"c-75"
		"ypos"			"r115"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit9b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit9b"
		"xpos"			"c-75"
		"ypos"			"r115"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit17f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit25f"
		"xpos"			"c-60"
		"ypos"			"r116"
		"zpos"			"7"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit17b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit25b"
		"xpos"			"c-60"
		"ypos"			"r116"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit26f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit26f"
		"xpos"			"c-45"
		"ypos"			"r115"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit26b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit26b"
		"xpos"			"c-45"
		"ypos"			"r115"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit33f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit25f"
		"xpos"			"c-30"
		"ypos"			"r116"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit33b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit33b"
		"xpos"			"c-30"
		"ypos"			"r116"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit42f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit42f"
		"xpos"			"c-15"
		"ypos"			"r115"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit42b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit42b"
		"xpos"			"c-15"
		"ypos"			"r115"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit50f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit50f"
		"xpos"			"c0"
		"ypos"			"r117"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"11"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit50b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit50b"
		"xpos"			"c0"
		"ypos"			"r117"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"11"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit59f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit59f"
		"xpos"			"c15"
		"ypos"			"r115"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit59b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit59b"
		"xpos"			"c15"
		"ypos"			"r115"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit67f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit67f"
		"xpos"			"c30"
		"ypos"			"r116"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit67b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit67b"
		"xpos"			"c30"
		"ypos"			"r116"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit76f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit76f"
		"xpos"			"c45"
		"ypos"			"r115"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit76b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit76b"
		"xpos"			"c45"
		"ypos"			"r115"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit83f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit83f"
		"xpos"			"c60"
		"ypos"			"r116"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit83b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit83b"
		"xpos"			"c60"
		"ypos"			"r116"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"9"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchB"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit92f"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit92f"
		"xpos"			"c75"
		"ypos"			"r115"
		"zpos"			"6"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraF"
		"PaintBackgroundType"	"0"
	}
	"StickyBarSlit92b"
	{
		"ControlName"		"ImagePanel"
		"fieldName"		"StickyBarSlit92b"
		"xpos"			"c75"
		"ypos"			"r115"
		"zpos"			"1"
		"wide"			"1"
		"tall"			"7"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"fillcolor"		"StickyNotchExtraB"
		"PaintBackgroundType"	"0"
	}
}
